#!/usr/bin/env python3

# twitcher-open
# -------------
# Open a twitch stream in VLC using python-livestreamer
# http://docs.livestreamer.io/

# Usage:
#     - ./twitcher-open [space-delimited streams]
#     - echo "stream1\nstream2" | ./twitcher-open

# Requires:
#     - Livestreamer command line utility

import os
import subprocess
import sys

prefix = "twitch.tv/"
command = ["livestreamer", None, "best"]
if len(sys.argv) > 1:
    for stream in sys.argv[1:]:
        command[1] = "".join([prefix, stream])
        subprocess.Popen(command, stdout=open(os.devnull, "w"))
else:
    for stream in sys.stdin:
        command[1] = "".join([prefix, stream.split()[0]])
        subprocess.Popen(command, stdout=open(os.devnull, "w"))
